name: Auto Doc Gen
on:
  push:
    branches:
      - master

env:
  NODE_VERSION: 16.x

jobs:
  docgen:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: master
    - run: git checkout HEAD

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies
      run: npm ci

    - name: Generate docs
      run: npm run docs

    - name: Check for modified doc files
      run: |
        if [[ $(git diff --stat docs || true) ]]; then
          echo "::set-output name=result::MODIFIED"
        else
          echo "::set-output name=result::UNMODIFIED"
        fi
      id: git-diff-check

    - if: steps.git-diff-check.outputs.result == 'MODIFIED'
      name: Commit and push changes
      run: |
        git config --global user.name 'SDK Docs Bot'
        git config --global user.email 'actions@users.noreply.github.com'
        git add docs
        git commit --no-verify -m "Auto generated Embed SDK docs - Github workflow @ .github/workflow/docs.yml"
        git push
